# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb3a6560d5ff40b0b0412ef65af92f746b79293b7d7da41e6a4a19fc4e1784cb149a82b619fb8dd2c3557226c028930bcf672ae4181b25a03eb71c1f049b97ee

test:
  secret_key_base: 549315a16cb72faa8d105a8514c13ae56295204305438fc00bfa115ca891d2483f64209762233e63382cda3959cd1a67cd82cf4c9ff554533c5a45257b2923de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
